spring:
  h2.console:
      enabled: true
      path: '/console'
  jpa:
    Hibernate:
      ddl-auto: validate
  datasource:
    url: 'jdbc:h2:file:./todo-db'

management:
  endpoints:
    web:
      exposure:
        include: '*'
